version: "3.5"
services:
  php:
    build:
      context: ./docker/php
      args:
        - UID
        - USER_NAME
    container_name: ${COMPOSE_PROJECT_NAME}_php
    volumes:
      - ./code:/code
    working_dir: /code
    user: ${USER_NAME}
    environment:
      PHP_IDE_CONFIG: "serverName=php_example"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      internal:

  redis:
    image: redis:6.0.5
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    networks:
      internal:

  rabbitmq:
    image: rabbitmq:3.8.5-management
    container_name: ${COMPOSE_PROJECT_NAME}_rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      internal:

  elasticsearch:
    image: elasticsearch:7.17.5
    container_name: ${COMPOSE_PROJECT_NAME}_elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms256m"
      discovery.type: single-node
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      internal:

  kibana:
    image: kibana:7.17.5
    container_name: ${COMPOSE_PROJECT_NAME}_kibana
    ports:
      - 5601:5601
    networks:
      internal:
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: ${COMPOSE_PROJECT_NAME}_kafka
    networks:
      internal:
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
  kafka-ui:
    container_name: ${COMPOSE_PROJECT_NAME}_kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: wizard_test
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      internal:
networks:
  internal:
    name: php_example_net
#    external:
#      name: wh_network
#    ipam:
#      driver: default
#      config:
#        - subnet: "172.30.0.0/16"
