version: "3.5"
services:
  php:
    build:
      context: ./docker/php
      args:
        - UID
        - USER_NAME
    container_name: ${COMPOSE_PROJECT_NAME}_php
    volumes:
      - ./code:/code
    working_dir: /code
    user: ${USER_NAME}
    environment:
      PHP_IDE_CONFIG: "serverName=php_example"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      internal:

  clickhouse-server:
    image: yandex/clickhouse-server
    container_name: ${COMPOSE_PROJECT_NAME}_clickhouse_server
    ports:
      - "8123:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./docker/clickhouse/volumes:/var/lib/clickhouse
    networks:
      internal:

networks:
  internal:
    name: php_example_net
