version: "3.5"
services:
  php:
    build:
      context: ./docker/php
      args:
        - UID
        - USER_NAME
    container_name: php_cli
    volumes:
      - ./code:/code
    working_dir: /code
    user: ${USER_NAME}
    environment:
      PHP_IDE_CONFIG: "serverName=php_example"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      example_net:

  redis:
    image: redis:6.0.5
    container_name: redis_cli
    networks:
      example_net:

  rabbitmq:
    image: rabbitmq:3.8.5-management
    container_name: rabbitmq_cli
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      example_net:

  elasticsearch:
    image: elasticsearch:7.8.0
    container_name: elasticsearch_cli
    environment:
      - "discovery.type=single-node"
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      example_net:

  kibana:
    image: kibana:7.8.0
    container_name: kibana_cli
    ports:
      - 5601:5601
    networks:
      example_net:
networks:
  example_net:
#    external:
#      name: wh_network
#    ipam:
#      driver: default
#      config:
#        - subnet: "172.30.0.0/16"
