version: "3.5"
services:
  php:
    build:
      context: ./.
      args:
        - UID
        - USER_NAME
    container_name: php_cli
    volumes:
      - ./..:/code
    working_dir: /code
    user: ${USER_NAME}

  redis:
    image: redis:6.0.5
    container_name: redis_cli