version: "3.5"
services:
  php:
    build:
      context: ./php
      args:
        - UID
        - USER_NAME
    container_name: php_cli
    volumes:
      - ./..:/code
    working_dir: /code
    user: ${USER_NAME}

  redis:
    image: redis:6.0.5
    container_name: redis_cli
    volumes:
      - "./redis/volumes:/data"

  rabbitmq:
    image: rabbitmq:3.8.5-management
    container_name: rabbitmq_cli
    ports:
      - 5672:5672
      - 15672:15672
