devac:
  hostname: dev.host.ru
  port: 22
  user: deployer
  deploy_path: /var/www/project
  branch: develop
  composer_options: '{{composer_action}} --verbose --prefer-dist --no-progress --no-interaction --optimize-autoloader --no-suggest'
  env:
    - SYMFONY_ENV: dev
  stage: devac
  keep_releases: 2
prodac:
  hostname: host.ru
  port: 22
  user: deployer
  deploy_path: /var/www/project
  branch: master
  stage: prodac
  keep_releases: 4
